
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Thu Jan 18 20:37:09 CET 2024
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int GREATER_EQ = 23;
  public static final int AND = 5;
  public static final int SEMICOLON = 17;
  public static final int ELSE = 3;
  public static final int OR = 4;
  public static final int CHAR = 8;
  public static final int WHILE = 2;
  public static final int LEFTPAR = 13;
  public static final int END = 12;
  public static final int GREATER = 22;
  public static final int INTCONST = 27;
  public static final int RIGHTPAR = 14;
  public static final int COLON = 15;
  public static final int ID = 26;
  public static final int PROGRAM = 6;
  public static final int BEGIN = 11;
  public static final int BOOLEAN = 10;
  public static final int COMMA = 18;
  public static final int EOF = 0;
  public static final int CHARCONST = 29;
  public static final int REALCONST = 28;
  public static final int DOT = 19;
  public static final int error = 1;
  public static final int EQ = 24;
  public static final int LESS_EQ = 21;
  public static final int ASSIGN = 16;
  public static final int INTEGER = 7;
  public static final int REAL = 9;
  public static final int BOOLCONST = 30;
  public static final int NOT_EQ = 25;
  public static final int LESS = 20;
}

